lib/palapa_web/router.ex
defmodule PalapaWeb.Router do
  use PalapaWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(Phoenix.LiveView.Flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)

    # Sets current_account
    plug(PalapaWeb.Authentication)
    plug(PalapaWeb.Locale)
  end

  pipeline :authentication do
    plug(:enforce_authentication)
  end

  pipeline :disable_feature do
    plug(PalapaWeb.DisableFeature)
  end

  pipeline :billing do
    plug(:enforce_billing)
  end

  pipeline :organization_context do
    plug(:put_organization_context)
  end

  pipeline :contact_navigation do
    plug(PalapaWeb.ContactNavigation)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  if Mix.env() == :dev do
    forward("/emails", Bamboo.SentEmailViewerPlug)
  end

  # Public pages
  scope "/", PalapaWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)
    get("/legal", HomeController, :legal)
    get("/terms", HomeController, :terms)
    resources("/beta_subscriptions", BetaSubscriptionController, only: [:index, :create])
    resources("/registrations", RegistrationController, only: [:new, :create])
    resources("/sessions", SessionController, only: [:new, :create, :delete], singleton: true)

    resources("/password_reset", PasswordResetController,
      only: [:new, :create, :edit, :update],
      singleton: true
    )

    get("/join/:invitation_id/:token", JoinController, :new)
    post("/join/:invitation_id/:token", JoinController, :create)
  end

  # Documents public sharing
  scope(path: "/public", as: :public, alias: PalapaWeb.Public) do
    pipe_through(:browser)

    resources("/documents", DocumentController, only: [:show]) do
      resources("/pages", PageController, only: [:show])
    end
  end

  scope("/", PalapaWeb) do
    pipe_through([:browser, :authentication])

    resources("/account", AccountController, only: [:edit, :update, :delete], singleton: true)
    resources("/organizations", OrganizationController, only: [:index, :new, :create])
  end

  scope("/organizations/:organization_id", PalapaWeb) do
    pipe_through([:browser, :authentication, :organization_context])

    delete("/", OrganizationController, :delete)

    scope("/billing", Billing) do
      resources("/subscription", SubscriptionController, only: [:new, :create], singleton: true)

      post("/subscription/refresh", SubscriptionController, :refresh)

      resources("/payment_method", PaymentMethodController,
        only: [:edit, :update],
        singleton: true
      )

      resources("/payment", PaymentController, only: [:new], singleton: true)

      resources("/billing_error", BillingErrorController,
        only: [:show],
        singleton: true
      )
    end

    scope "/settings", Settings, as: :settings do
      resources("/workspace", WorkspaceController, singleton: true)
      resources("/members", MemberController, only: [:index, :delete])

      resources("/customer", Billing.CustomerController,
        singleton: true,
        only: [:show, :edit, :update]
      )

      resources("/payment_method", Billing.PaymentMethodController,
        singleton: true,
        only: [:edit, :update]
      )
    end
  end

  # Private pages for logged in members only
  scope("/organizations/:organization_id", PalapaWeb) do
    pipe_through([:browser, :authentication, :organization_context, :billing])

    get("/", MessageController, :index)
    get("/search", SearchController, :index)
    resources("/attachments", AttachmentController, only: [:create, :show])
    resources("/trash", TrashController, only: [:index])

    # --- MESSAGES

    resources("/messages", MessageController) do
      resources("/comments", MessageCommentController, only: [:create])
    end

    resources("/messages/comments", MessageCommentController, only: [:edit, :update, :delete])

    # --- DOCUMENTS

    resources("/documents", Document.DocumentController) do
      resources("/trash", Document.DocumentTrashController,
        singleton: true,
        only: [:create, :delete],
        as: :trash
      )

      resources("/public_link", Document.DocumentPublicLinkController,
        singleton: true,
        only: [:create, :delete],
        as: :public_link
      )

      resources("/sections", Document.SectionController, only: [:create])
      resources("/page", Document.PageController, only: [:new, :create])
    end

    resources("/documents/sections", Document.SectionController,
      only: [:edit, :update, :delete],
      as: :document_section
    )

    resources("/documents/pages", Document.PageController,
      only: [:show, :edit, :update, :delete],
      as: :document_page
    ) do
      resources("/suggestions", Document.SuggestionController, only: [:index, :create])
    end

    resources("/documents/suggestions", Document.SuggestionController,
      only: [:edit, :update, :delete]
    ) do
      resources("/comments", Document.SuggestionCommentController,
        only: [:create],
        as: :comment
      )

      resources("/closure", Document.SuggestionClosureController,
        only: [:create, :delete],
        as: :closure,
        singleton: true
      )
    end

    resources("/documents/suggestions/comments", Document.SuggestionCommentController,
      only: [:edit, :update, :delete]
    )

    # --- CONTACTS

    scope "/" do
      pipe_through([:contact_navigation])
      get("/contacts/export", ContactExportController, :index)
      live "/contacts", ContactLive, session: [:account_id]
      live "/contacts/new", ContactLive.New, session: [:account_id]
      live "/contacts/:id", ContactLive, session: [:account_id]
      live "/contacts/:id/edit", ContactLive.Edit, session: [:account_id]
    end

    # --- MEMBERS

    resources "/members", MemberController, only: [:index, :show] do
      resources("/teams", TeamMemberController, only: [:edit, :update], singleton: true)
    end

    resources("/invitations", InvitationController, only: [:new, :create, :delete]) do
      post("/renewal", InvitationController, :renew, as: :renew)
    end

    resources("/teams", TeamController, only: [:new, :create, :edit, :update, :delete]) do
      resources(
        "/membership",
        TeamMembershipController,
        only: [:create, :delete],
        singleton: true
      )
    end

    # --- PROFILE

    resources("/profile", ProfileController, only: [:edit, :update])
  end

  scope "/", PalapaWeb do
    pipe_through :api
    post("/stripe_webhooks", Billing.StripeWebhookController, :create)
  end

  # scope "/api", PalapaWeb do
  #   pipe_through :api
  # end
end

lib/palapa_web/views/layout_view.ex
defmodule PalapaWeb.LayoutView do
  use PalapaWeb, :view
end

lib/palapa_web/templates/layout/_breadcrumbs.html.eex
<%= if assigns[:breadcrumbs] do %>
  <nav class="navigation">
    <ol class="breadcrumbs">
      <li class="breadcrumb-item">
        <%= link to: Routes.message_path(@conn, :index, @current_organization) do %>
          <i class="fas fa-home"></i>
        <% end %>
      </li>

      <%= for breadcrumb <- @breadcrumbs do %>
        <li class="breadcrumb-item">
          <span><%= link breadcrumb[:title], to: breadcrumb[:href] %></span>
        </li>
      <% end %>
    </ol>
  </nav>
<% end %>

lib/palapa_web/templates/layout/_flash_notice.html.eex
<div class="flash">
  <div data-controller="flash">
    <%= if get_flash(@conn, :success) do %>
      <div class="text-center">
        <div class="p-2 bg-green-400 items-center text-white leading-none lg:rounded-full flex lg:inline-flex" role="alert">
          <span class="font-semibold mr-2 text-left flex-auto"><i class="fas fa-check-circle"></i>
          <%= get_flash(@conn, :success) %></span>
        </div>
      </div>
    <% end %>

    <%= if get_flash(@conn, :info) do %>
      <div class="text-center">
        <div class="p-2 bg-blue-600 items-center text-blue-100 leading-none lg:rounded-full flex lg:inline-flex" role="alert">
          <span class="flex rounded-full bg-blue-500 uppercase px-2 py-1 text-xs font-bold mr-3">Info</span>
          <span class="font-semibold mr-2 text-left flex-auto"><%= get_flash(@conn, :info) %></span>
        </div>
      </div>
    <% end %>

    <%= if get_flash(@conn, :error) do %>
      <div class="text-center">
        <div class="p-2 bg-red-400 items-center text-white leading-none lg:rounded-full flex lg:inline-flex" role="alert">
          <span class="font-semibold mr-2 text-left flex-auto"><i class="fas fa-exclamation-circle"></i>
          <%= get_flash(@conn, :error) %></span>
        </div>
      </div>
    <% end %>
    </div>
</div>

lib/palapa_web/templates/layout/_private_navigation.html.eex
<header class="header">
  <nav data-controller="navigation" class="flex items-center justify-between lg:justify-between p-1">
    <button data-action="navigation#toggleMobileMenu" class="lg:hidden px-2 py-1 hover:bg-green-300 border my-1 font-bold rounded">
      <i class="fas fa-bars text-green-500"></i><span class="ml-2 hidden sm:inline-block">Menu</span>
    </button>

    <div class="hidden lg:block">
      <%= render PalapaWeb.LayoutView, "_breadcrumbs.html", assigns %>
    </div>

    <div class="flex items-center">

      <div class="hidden lg:inline-block" data-controller="popover" data-action="mousedown@window->popover#hide">
        <button data-target="popover.button" data-action="popover#toggle" class="btn rounded-full">
          <i class="fas fa-plus-circle text-green-500 mr-2"></i><%= gettext("Create") %><i class="fas fa-angle-down ml-2"></i>
        </button>

        <div data-target="popover.content" class="popover hidden">
          <div data-target="popover.arrow" class="popover__arrow"></div>
          <nav class="flex flex-col">
            <%= link to: Routes.message_path(@conn, :new, @current_organization), class: "popover__link" do %>
              <i class="fas fa-comment mr-2"></i><%= gettext("Message") %>
            <% end %>

            <%= link to: Routes.document_path(@conn, :new, @current_organization), class: "popover__link" do %>
              <i class="fas fa-file-alt mr-2"></i><%= gettext("Document") %>
            <% end %>

            <%= link to: Routes.live_path(@conn, PalapaWeb.ContactLive.New, @current_organization), class: "popover__link" do %>
              <i class="fas fa-address-book mr-2"></i><%= gettext("Contact") %>
            <% end %>

            <%= if permit?(Palapa.Teams.Policy, :create, @current_member) do %>
              <%= link to: Routes.team_path(@conn, :new, @current_organization), class: "popover__link" do %>
                <i class="fas fa-users mr-2"></i><%= gettext("Team") %>
              <% end %>
            <% end %>
          </nav>
        </div>
      </div>

      <div id="global-search" class="flex-shrink mx-1 lg:mx-4" data-controller="search" data-search-index="0" data-search-active="false">
        <div data-action="click@window->search#escapeSearchDialog">
          <%= form_for @conn, Routes.search_path(@conn, :index, @current_organization), [method: :get, "data-target": "search.form"], fn _form -> %>
            <div class="search-bar bg-white">
              <span class="fa fa-search mr-2"></span>
              <input type="text" name="query" data-target="search.queryInput" data-action="input->search#triggerSearch keydown->search#triggerKeyNavigation" autocomplete="off" placeholder="<%= gettext("Search anything") %>" />
            </div>

          <% end %>

          <div data-target="search.searchDialog" class="search__results-container hidden">
            <div data-target="search.searchingIndicator" class="text-gray-500 text-sm text-center"><%= gettext("Searching...") %></div>
            <div data-target="search.resultsContainer"></div>
          </div>
        </div>
      </div>

      <div class="lg:mx-4">
        <a href="#" data-action="navigation#showSwitcher" title="Signed id as <%= @current_account.name %>"><%= Helpers.avatar(@current_account, :sm) %></a>
        <div data-target="navigation.switcher" class="text-sm hidden absolute right-0 z-100 py-4 px-8 bg-white shadow-lg rounded">
          <div class="relative">
            <div class="text-gray-800 font-bold mb-2 py-1"><%= @current_account.name %></div>

            <ul class="mb-2">
              <li><%= link(gettext("My profile", %{workspace: @current_organization.name}), to: Routes.member_path(@conn, :show, @current_organization, @current_member), class: "text-blue-500 hover:underline") %></li>
              <li><%= link(gettext("Preferences"), to: Routes.account_path(@conn, :edit), class: "text-blue-500 hover:underline") %></li>
              <li><%= link(gettext("Switch workspace"), to: Routes.organization_path(@conn, :index), class: "text-blue-500 hover:underline") %></li>
            </ul>
            <ul class="mb-4">
              <li class="mt-4"><%= link(gettext("Log out"), to: Routes.session_path(@conn, :delete), class: "btn font-bold text-red-400 hover:underline", data: [controller: "link", action: "link#delete"]) %></li>
            </ul>
          </div>
        </div>
      </div>

    </div>

  </nav>
</header>

lib/palapa_web/templates/layout/_public_navigation.html.eex
<nav class="flex items-center justify-between flex-wrap p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6 mb-4">
    <span class="font-semibold text-xl tracking-tighter">
      <%= link(to: Routes.home_path(@conn, :index)) do %>
        <img src="<%= Routes.static_path(@conn, "/images/logo_palapa-x2.png") %>" alt="Palapa">
      <% end %>
    </span>
  </div>

  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">

    </div>

    <div class="flex flex-wrap">
      <%= link(gettext("Create workspace"), to: Routes.registration_path(@conn, :new), class: "btn btn-green mr-2") %>
      <%= if @conn.assigns[:current_account] do %>
        <%= link(gettext("Sign out"), to: Routes.session_path(@conn, :delete), data: [controller: "link", action: "link#delete"], class: "btn ") %>
      <% else %>
        <%= link(gettext("Sign in"), to: Routes.session_path(@conn, :new), class: "btn ") %>
      <% end%>
    </div>
  </div>
</nav>

lib/palapa_web/templates/layout/_sidebar.html.eex
<div class="sidebar">
  <div id="toggle-mobile-menu" class="mb-8" data-controller="navigation">
    <button data-action="navigation#toggleMobileMenu" class="flex items-center mx-auto px-3 py-2 border-2 rounded text-green-500 border-green-500 hover:text-green-600 hover:border-green-600">
      <i class="fas fa-times mr-2"></i><%= gettext("Close menu") %>
    </button>
  </div>

  <%= link to: Routes.organization_path(@conn, :index),
    class: "-m-4 mb-4 bg-gray-500 rounded-r-lg p-2 text-center font-bold text-gray-800 text-xs border-t border-b border-r border-gray-800 hover:bg-gray-100" do %>
    <i class="fas fa-exchange-alt mr-2"></i><%= gettext("Switch workspace") %>
  <% end %>

  <%= link(@current_organization.name, to: Routes.message_path(@conn, :index, @current_organization), class: "text-lg font-bold px-2 mt-8 block text-white tracking-wider") %>

  <ul class="header-links">
    <li class="header-link <%= if @navigation == "message" do %>header-link--active<% end %>">
      <%= link(to: Routes.message_path(@conn, :index, @current_organization), class: "block") do %>
        <i class="fas fa-bullhorn mr-2"></i><%= gettext("What's up?") %>
      <% end %>
    </li>

    <li class="header-link  <%= if @navigation == "documents" do %>header-link--active<% end %>">
      <%= link(to: Routes.document_path(@conn, :index, @current_organization), class: "block") do %>
        <i class="fas fa-file-alt mr-2"></i><%= gettext("Documents") %>
      <% end %>
    </li>

    <li class="header-link  <%= if @navigation == "contacts" do %>header-link--active<% end %>">
      <%= link(to: Routes.live_path(@conn, PalapaWeb.ContactLive, @current_organization), class: "block") do %>
        <i class="fas fa-address-book mr-2"></i><%= gettext("Contacts") %>
      <% end %>
    </li>

    <li class="header-link  <%= if @navigation == "members" do %>header-link--active<% end %>">
      <%= link(to: Routes.member_path(@conn, :index, @current_organization), class: "block") do %>
        <i class="fas fa-users mr-2"></i><%= gettext("Teams") %>
      <% end %>
    </li>

    <%= if permit?(Palapa.Organizations.Policy, :update_organization, @current_member) do %>
      <li class="header-link  <%= if @navigation == "settings" do %>header-link--active<% end %>">
        <%= link(to: Routes.settings_workspace_path(@conn, :show, @current_organization), class: "block") do %>
          <i class="fas fa-cog mr-2"></i><%= gettext("Settings") %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

lib/palapa_web/templates/layout/account.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tag() %>
    <title><%= @current_account.name %> | Palapa</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="float-right m-4"><%= link(gettext("Log out"), to: Routes.session_path(@conn, :delete), class: "btn", data: [controller: "link", action: "link#delete"]) %></div>
    <div class="lg:max-w-2xl mx-auto">
      <div class="flex justify-center mb-8 pt-4">
        <%= Helpers.avatar(@current_account, :sm) %>
        <span class="ml-2 self-center text-gray-800 font-bold"><%= @current_account.name %></span>
      </div>

      <nav class="my-4">
        <div class="-mb-px flex justify-center">
          <%= link gettext("Your workspaces"), to: Routes.organization_path(@conn, :index), class: Helpers.auto_active_tab(@navigation, "workspaces") %>
          <%= link gettext("Account settings"), to: Routes.account_path(@conn, :edit), class: Helpers.auto_active_tab(@navigation, "account") %>
        </div>
      </nav>

      <main role="main">
        <%= render PalapaWeb.LayoutView, "_flash_notice.html", assigns %>
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>

    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/palapa_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tag() %>
    <title><%= Helpers.get_page_title(@conn) %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <script defer src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body class="layout">
    <%= render PalapaWeb.LayoutView, "_sidebar.html", assigns %>

    <div class="main">
      <%= render PalapaWeb.LayoutView, "_private_navigation.html", assigns %>
      <%= render PalapaWeb.LayoutView, "_flash_notice.html", assigns %>
      <%= render @view_module, @view_template, assigns %>

      <footer class="footer py-8 mt-8 text-center text-xs text-gray-600">
      </footer>
    </div>
  </body>
</html>

lib/palapa_web/templates/layout/home.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">
    <meta name="description" content="Palapa is your team headquarters. Get multiple collaborative tools such as a Message Board, a Knowledge Base, and a Contact Book in the same application. Each one remaining super simple to use with only the essential features.">
    <meta name="author" content="Palapa">

    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">


    <%# Google analytics %>
    <%= if Application.get_env(:palapa, :env) == :prod do %>
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-126862170-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-126862170-1');
      </script>
    <% end %>

    <title>Palapa, your team headquarters</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app_front.css") %>">
    <link href="https://rsms.me/inter/inter.css" rel="stylesheet">
    <script src="https://unpkg.com/feather-icons"></script>
  </head>

  <body class="leading-normal text-gray-900">
    <%= render @view_module, @view_template, assigns %>
    <script src="<%= Routes.static_path(@conn, "/js/app_front.js") %>"></script>
  </body>
</html>

lib/palapa_web/templates/layout/minimal.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tag() %>
    <title>Palapa</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render PalapaWeb.LayoutView, "_flash_notice.html", assigns %>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/palapa_web/templates/layout/public.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tag() %>
    <title>Palapa</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render PalapaWeb.LayoutView, "_public_navigation.html", assigns %>
    <%= render PalapaWeb.LayoutView, "_flash_notice.html", assigns %>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>