lib/palapa_web/router.ex
defmodule PalapaWeb.Router do
  use PalapaWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(Phoenix.LiveView.Flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)

    # Sets current_account
    plug(PalapaWeb.Authentication)
    plug(PalapaWeb.Locale)
  end

  pipeline :authentication do
    plug(:enforce_authentication)
  end

  pipeline :disable_feature do
    plug(PalapaWeb.DisableFeature)
  end

  pipeline :billing do
    plug(:enforce_billing)
  end

  pipeline :organization_context do
    plug(:put_organization_context)
  end

  pipeline :contact_navigation do
    plug(PalapaWeb.ContactNavigation)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  if Mix.env() == :dev do
    forward("/emails", Bamboo.SentEmailViewerPlug)
  end

  # Public pages
  scope "/", PalapaWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)
    get("/legal", HomeController, :legal)
    get("/terms", HomeController, :terms)
    resources("/beta_subscriptions", BetaSubscriptionController, only: [:index, :create])
    resources("/registrations", RegistrationController, only: [:new, :create])
    resources("/sessions", SessionController, only: [:new, :create, :delete], singleton: true)

    resources("/password_reset", PasswordResetController,
      only: [:new, :create, :edit, :update],
      singleton: true
    )

    get("/join/:invitation_id/:token", JoinController, :new)
    post("/join/:invitation_id/:token", JoinController, :create)
  end

  # Documents public sharing
  scope(path: "/public", as: :public, alias: PalapaWeb.Public) do
    pipe_through(:browser)

    resources("/documents", DocumentController, only: [:show]) do
      resources("/pages", PageController, only: [:show])
    end
  end

  scope("/", PalapaWeb) do
    pipe_through([:browser, :authentication])

    resources("/account", AccountController, only: [:edit, :update, :delete], singleton: true)
    resources("/organizations", OrganizationController, only: [:index, :new, :create])
  end

  scope("/organizations/:organization_id", PalapaWeb) do
    pipe_through([:browser, :authentication, :organization_context])

    delete("/", OrganizationController, :delete)

    scope("/billing", Billing) do
      resources("/subscription", SubscriptionController, only: [:new, :create], singleton: true)

      post("/subscription/refresh", SubscriptionController, :refresh)

      resources("/payment_method", PaymentMethodController,
        only: [:edit, :update],
        singleton: true
      )

      resources("/payment", PaymentController, only: [:new], singleton: true)

      resources("/billing_error", BillingErrorController,
        only: [:show],
        singleton: true
      )
    end

    scope "/settings", Settings, as: :settings do
      resources("/workspace", WorkspaceController, singleton: true)
      resources("/members", MemberController, only: [:index, :delete])

      resources("/customer", Billing.CustomerController,
        singleton: true,
        only: [:show, :edit, :update]
      )

      resources("/payment_method", Billing.PaymentMethodController,
        singleton: true,
        only: [:edit, :update]
      )
    end
  end

  # Private pages for logged in members only
  scope("/organizations/:organization_id", PalapaWeb) do
    pipe_through([:browser, :authentication, :organization_context, :billing])

    get("/", MessageController, :index)
    get("/search", SearchController, :index)
    resources("/attachments", AttachmentController, only: [:create, :show])
    resources("/trash", TrashController, only: [:index])

    # --- MESSAGES

    resources("/messages", MessageController) do
      resources("/comments", MessageCommentController, only: [:create])
    end

    resources("/messages/comments", MessageCommentController, only: [:edit, :update, :delete])

    # --- DOCUMENTS

    resources("/documents", Document.DocumentController) do
      resources("/trash", Document.DocumentTrashController,
        singleton: true,
        only: [:create, :delete],
        as: :trash
      )

      resources("/public_link", Document.DocumentPublicLinkController,
        singleton: true,
        only: [:create, :delete],
        as: :public_link
      )

      resources("/sections", Document.SectionController, only: [:create])
      resources("/page", Document.PageController, only: [:new, :create])
    end

    resources("/documents/sections", Document.SectionController,
      only: [:edit, :update, :delete],
      as: :document_section
    )

    resources("/documents/pages", Document.PageController,
      only: [:show, :edit, :update, :delete],
      as: :document_page
    ) do
      resources("/suggestions", Document.SuggestionController, only: [:index, :create])
    end

    resources("/documents/suggestions", Document.SuggestionController,
      only: [:edit, :update, :delete]
    ) do
      resources("/comments", Document.SuggestionCommentController,
        only: [:create],
        as: :comment
      )

      resources("/closure", Document.SuggestionClosureController,
        only: [:create, :delete],
        as: :closure,
        singleton: true
      )
    end

    resources("/documents/suggestions/comments", Document.SuggestionCommentController,
      only: [:edit, :update, :delete]
    )

    # --- CONTACTS

    scope "/" do
      pipe_through([:contact_navigation])
      get("/contacts/export", ContactExportController, :index)
      live "/contacts", ContactLive, session: [:account_id]
      live "/contacts/new", ContactLive.New, session: [:account_id]
      live "/contacts/:id", ContactLive, session: [:account_id]
      live "/contacts/:id/edit", ContactLive.Edit, session: [:account_id]
    end

    # --- MEMBERS

    resources "/members", MemberController, only: [:index, :show] do
      resources("/teams", TeamMemberController, only: [:edit, :update], singleton: true)
    end

    resources("/invitations", InvitationController, only: [:new, :create, :delete]) do
      post("/renewal", InvitationController, :renew, as: :renew)
    end

    resources("/teams", TeamController, only: [:new, :create, :edit, :update, :delete]) do
      resources(
        "/membership",
        TeamMembershipController,
        only: [:create, :delete],
        singleton: true
      )
    end

    # --- PROFILE

    resources("/profile", ProfileController, only: [:edit, :update])
  end

  scope "/", PalapaWeb do
    pipe_through :api
    post("/stripe_webhooks", Billing.StripeWebhookController, :create)
  end

  # scope "/api", PalapaWeb do
  #   pipe_through :api
  # end
end

lib/palapa_web/controllers/password_reset_controller.ex
defmodule PalapaWeb.PasswordResetController do
  use PalapaWeb, :controller

  alias Palapa.Accounts

  plug(:put_layout, "public.html")

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, %{"password_reset" => %{"email" => email}}) do
    if email && email =~ ~r/@/ do
      account = Accounts.get_by(email: email)

      if account do
        {:ok, password_reset_token} = Accounts.generate_password_reset_token(account)

        Accounts.Emails.password_reset(account, password_reset_token)
        |> Palapa.Mailer.deliver_now()
      end

      render(conn, "create.html", email: email)
    else
      conn
      |> put_flash(:error, gettext("Please enter a valid email address"))
      |> render("new.html")
    end
  end

  def edit(conn, %{"password_reset_token" => token}) do
    account = Accounts.find_account_by_password_reset_token(token)

    if account do
      render(conn, "edit.html",
        account: account,
        password_reset_token: token,
        password_changeset: Accounts.Account.password_reset_changeset(account, %{})
      )
    else
      conn
      |> put_flash(:error, gettext("Invalid token"))
      |> render("invalid_token.html")
    end
  end

  def update(conn, %{"password" => password_attrs}) do
    account =
      Accounts.find_account_by_password_reset_token(password_attrs["password_reset_token"])

    if account do
      case Accounts.reset_password(account, password_attrs) do
        {:ok, account} ->
          conn
          |> PalapaWeb.Authentication.start_session(account)
          |> redirect(to: Routes.organization_path(conn, :index))

        {:error, changeset} ->
          conn
          |> put_flash(:error, gettext("Cannot update the password"))
          |> render("edit.html",
            account: account,
            password_reset_token: password_attrs["password_reset_token"],
            password_changeset: changeset
          )
      end
    else
      conn
      |> put_flash(:error, "Invalid token")
      |> render("invalid_token.html")
    end
  end
end

lib/palapa_web/views/password_reset_view.ex
defmodule PalapaWeb.PasswordResetView do
  use PalapaWeb, :view
end

lib/palapa_web/templates/password_reset/create.html.eex
<div class="flex justify-center">
  <div class="w-full max-w-sm">
    <div class="card p-8">
      <h2 class="card-header"><%= gettext("Password reset") %></h2>

      <div class="card-header-separator"></div>

      <p><%= raw gettext("An email has been sent to %{email}.", %{email: "<strong>#{@email}</strong>"}) %><br><%= gettext("Check your inbox and click the given link to reset your password.") %></p>
    </div>
  </div>
</div>

lib/palapa_web/templates/password_reset/edit.html.eex
<div class="flex justify-center">
  <div class="w-full max-w-sm">
    <div class="card p-8">
      <h2 class="card-header"><%= gettext("Change your password") %></h2>
      <div class="card-header-separator"></div>

      <%= form_for @password_changeset, Routes.password_reset_path(@conn, :update), [as: :password], fn form -> %>
        <%= if @password_changeset.action do %>
          <p class="db fw6 lh-copy f6  text-red-400 font-bold"><%= gettext("Check the errors below:") %></p>
        <% end %>

        <div class="field">
          <%= label form, :password, gettext("New password"), class: "label" %>
          <%= password_input form, :password, class: "input", autocomplete: "off" %>
          <%= error_tag form, :password %>
        </div>

        <div class="field">
          <%= label form, :password_confirmation, gettext("Confirm the new password"), class: "label" %>
          <%= password_input form, :password_confirmation, class: "input", autocomplete: "off" %>
          <%= error_tag form, :password_confirmation %>
        </div>

        <%= hidden_input form, :email, value: @account.email %>
        <%= hidden_input form, :password_reset_token, value: @password_reset_token %>

        <div class="card-actions">
          <%= submit gettext("Change password"), class: "btn btn-green"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

lib/palapa_web/templates/password_reset/invalid_token.html.eex
<div class="flex justify-center">
  <div class="w-full max-w-sm">
    <div class="card p-8">
      <h2 class="card-header"><%= gettext("Password reset") %></h2>

      <div class="card-header-separator"></div>

      <p>
        <%= raw gettext("This reset token is invalid or expired. If you've asked for a password reset more than an hour ago, please ask for a %{reset_link}",
        %{reset_link: safe_to_string(link(gettext("new reset link"),
          to: Routes.password_reset_path(@conn, :new), class: "text-blue-500 hover:underline"))}) %>
      </p>
    </div>
  </div>
</div>

lib/palapa_web/templates/password_reset/new.html.eex
<div class="flex justify-center">
  <div class="w-full max-w-sm">
    <div class="card p-8">
      <h2 class="card-header"><%= gettext("Password reset") %></h2>

      <div class="card-header-separator"></div>

      <%= form_for @conn, Routes.password_reset_path(@conn, :create), [as: :password_reset], fn f -> %>
        <p class="text-sm"><%= gettext("Enter the email address associated with your Palapa account. We will send you an email with reset instructions.") %></p>

        <div class="field">
          <%= label f, :email, gettext("Your email address"), class: "label" %>
          <%= email_input f, :email, class: "input" %>
        </div>

        <div class="card-actions">
          <%= submit gettext("Reset password"), class: "btn btn-green" %>
        </div>
      <% end %>
    </div>
  </div>
</div>