lib/palapa_web/router.ex
defmodule PalapaWeb.Router do
  use PalapaWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(Phoenix.LiveView.Flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)

    # Sets current_account
    plug(PalapaWeb.Authentication)
    plug(PalapaWeb.Locale)
  end

  pipeline :authentication do
    plug(:enforce_authentication)
  end

  pipeline :disable_feature do
    plug(PalapaWeb.DisableFeature)
  end

  pipeline :billing do
    plug(:enforce_billing)
  end

  pipeline :organization_context do
    plug(:put_organization_context)
  end

  pipeline :contact_navigation do
    plug(PalapaWeb.ContactNavigation)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  if Mix.env() == :dev do
    forward("/emails", Bamboo.SentEmailViewerPlug)
  end

  # Public pages
  scope "/", PalapaWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)
    get("/legal", HomeController, :legal)
    get("/terms", HomeController, :terms)
    resources("/beta_subscriptions", BetaSubscriptionController, only: [:index, :create])
    resources("/registrations", RegistrationController, only: [:new, :create])
    resources("/sessions", SessionController, only: [:new, :create, :delete], singleton: true)

    resources("/password_reset", PasswordResetController,
      only: [:new, :create, :edit, :update],
      singleton: true
    )

    get("/join/:invitation_id/:token", JoinController, :new)
    post("/join/:invitation_id/:token", JoinController, :create)
  end

  # Documents public sharing
  scope(path: "/public", as: :public, alias: PalapaWeb.Public) do
    pipe_through(:browser)

    resources("/documents", DocumentController, only: [:show]) do
      resources("/pages", PageController, only: [:show])
    end
  end

  scope("/", PalapaWeb) do
    pipe_through([:browser, :authentication])

    resources("/account", AccountController, only: [:edit, :update, :delete], singleton: true)
    resources("/organizations", OrganizationController, only: [:index, :new, :create])
  end

  scope("/organizations/:organization_id", PalapaWeb) do
    pipe_through([:browser, :authentication, :organization_context])

    delete("/", OrganizationController, :delete)

    scope("/billing", Billing) do
      resources("/subscription", SubscriptionController, only: [:new, :create], singleton: true)

      post("/subscription/refresh", SubscriptionController, :refresh)

      resources("/payment_method", PaymentMethodController,
        only: [:edit, :update],
        singleton: true
      )

      resources("/payment", PaymentController, only: [:new], singleton: true)

      resources("/billing_error", BillingErrorController,
        only: [:show],
        singleton: true
      )
    end

    scope "/settings", Settings, as: :settings do
      resources("/workspace", WorkspaceController, singleton: true)
      resources("/members", MemberController, only: [:index, :delete])

      resources("/customer", Billing.CustomerController,
        singleton: true,
        only: [:show, :edit, :update]
      )

      resources("/payment_method", Billing.PaymentMethodController,
        singleton: true,
        only: [:edit, :update]
      )
    end
  end

  # Private pages for logged in members only
  scope("/organizations/:organization_id", PalapaWeb) do
    pipe_through([:browser, :authentication, :organization_context, :billing])

    get("/", MessageController, :index)
    get("/search", SearchController, :index)
    resources("/attachments", AttachmentController, only: [:create, :show])
    resources("/trash", TrashController, only: [:index])

    # --- MESSAGES

    resources("/messages", MessageController) do
      resources("/comments", MessageCommentController, only: [:create])
    end

    resources("/messages/comments", MessageCommentController, only: [:edit, :update, :delete])

    # --- DOCUMENTS

    resources("/documents", Document.DocumentController) do
      resources("/trash", Document.DocumentTrashController,
        singleton: true,
        only: [:create, :delete],
        as: :trash
      )

      resources("/public_link", Document.DocumentPublicLinkController,
        singleton: true,
        only: [:create, :delete],
        as: :public_link
      )

      resources("/sections", Document.SectionController, only: [:create])
      resources("/page", Document.PageController, only: [:new, :create])
    end

    resources("/documents/sections", Document.SectionController,
      only: [:edit, :update, :delete],
      as: :document_section
    )

    resources("/documents/pages", Document.PageController,
      only: [:show, :edit, :update, :delete],
      as: :document_page
    ) do
      resources("/suggestions", Document.SuggestionController, only: [:index, :create])
    end

    resources("/documents/suggestions", Document.SuggestionController,
      only: [:edit, :update, :delete]
    ) do
      resources("/comments", Document.SuggestionCommentController,
        only: [:create],
        as: :comment
      )

      resources("/closure", Document.SuggestionClosureController,
        only: [:create, :delete],
        as: :closure,
        singleton: true
      )
    end

    resources("/documents/suggestions/comments", Document.SuggestionCommentController,
      only: [:edit, :update, :delete]
    )

    # --- CONTACTS

    scope "/" do
      pipe_through([:contact_navigation])
      get("/contacts/export", ContactExportController, :index)
      live "/contacts", ContactLive, session: [:account_id]
      live "/contacts/new", ContactLive.New, session: [:account_id]
      live "/contacts/:id", ContactLive, session: [:account_id]
      live "/contacts/:id/edit", ContactLive.Edit, session: [:account_id]
    end

    # --- MEMBERS

    resources "/members", MemberController, only: [:index, :show] do
      resources("/teams", TeamMemberController, only: [:edit, :update], singleton: true)
    end

    resources("/invitations", InvitationController, only: [:new, :create, :delete]) do
      post("/renewal", InvitationController, :renew, as: :renew)
    end

    resources("/teams", TeamController, only: [:new, :create, :edit, :update, :delete]) do
      resources(
        "/membership",
        TeamMembershipController,
        only: [:create, :delete],
        singleton: true
      )
    end

    # --- PROFILE

    resources("/profile", ProfileController, only: [:edit, :update])
  end

  scope "/", PalapaWeb do
    pipe_through :api
    post("/stripe_webhooks", Billing.StripeWebhookController, :create)
  end

  # scope "/api", PalapaWeb do
  #   pipe_through :api
  # end
end

lib/palapa_web/controllers/member_controller.ex
defmodule PalapaWeb.MemberController do
  use PalapaWeb, :controller
  alias Palapa.Teams
  alias Palapa.Organizations

  plug(:put_navigation, "members")
  plug(:put_common_breadcrumbs)

  def put_common_breadcrumbs(conn, _params) do
    conn
    |> put_breadcrumb(
      gettext("Teams"),
      Routes.member_path(conn, :index, current_organization(conn))
    )
  end

  def index(conn, %{"team_id" => team_id}) do
    with :ok <- permit(Organizations.Policy, :list_members, current_member(conn)) do
      selected_team = Teams.where_organization(current_organization(conn)) |> Teams.get!(team_id)
      members = Teams.list_members(selected_team)
      teams = Teams.where_organization(current_organization(conn)) |> Teams.list()
      organization_members_count = current_organization(conn) |> Organizations.members_count()

      conn
      |> put_breadcrumb(
        selected_team.name,
        Routes.member_path(conn, :index, current_organization(conn), team_id: team_id)
      )
      |> render(
        "index.html",
        members: members,
        teams: teams,
        selected_team: selected_team,
        organization_members_count: organization_members_count
      )
    end
  end

  def index(conn, _params) do
    with :ok <- permit(Organizations.Policy, :list_members, current_member(conn)) do
      members =
        current_organization(conn)
        |> Organizations.list_members()

      teams = Teams.where_organization(current_organization(conn)) |> Teams.list()

      conn
      |> render(
        "index.html",
        members: members,
        teams: teams,
        selected_team: nil,
        organization_members_count: length(members)
      )
    end
  end

  def show(conn, %{"id" => id}) do
    member = Organizations.get_member!(current_organization(conn), id)

    with :ok <- permit(Organizations.Policy, :show_member, current_member(conn)) do
      all_teams = Teams.where_organization(current_organization(conn)) |> Teams.list()

      conn
      |> put_breadcrumb(
        member.account.name,
        Routes.member_path(conn, :show, current_organization(conn), member)
      )
      |> render(
        "show.html",
        member: member,
        all_teams: all_teams
      )
    end
  end
end

lib/palapa_web/controllers/settings/member/member_controller.ex
defmodule PalapaWeb.Settings.MemberController do
  use PalapaWeb, :controller
  alias Palapa.Organizations

  plug Bodyguard.Plug.Authorize,
    policy: Palapa.Organizations.Policy,
    action: :update_organization,
    user: {PalapaWeb.Current, :current_member},
    fallback: PalapaWeb.FallbackController

  plug :put_navigation, "settings"
  plug :put_settings_navigation, "members"
  plug :put_common_breadcrumbs

  def put_settings_navigation(conn, value) do
    assign(conn, :settings_navigation, value)
  end

  def put_common_breadcrumbs(conn, _params) do
    conn
    |> put_breadcrumb(
      gettext("Settings"),
      Routes.settings_workspace_path(conn, :show, current_organization(conn))
    )
  end

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def delete(conn, _params) do
    with :ok <-
           permit(
             Organizations.Policy,
             :leave_organization,
             current_member(conn),
             current_organization(conn)
           ) do
      Organizations.delete_member(current_member(conn))

      conn
      |> put_flash(
        :success,
        gettext("You have left %{workspace}", %{workspace: current_organization(conn).name})
      )
      |> redirect(to: Routes.organization_path(conn, :index))
    end
  end
end

lib/palapa_web/live/member/member_profile_live.ex
defmodule PalapaWeb.MemberProfileLive do
  use PalapaWeb, :live_view

  alias Palapa.Organizations
  alias Palapa.Accounts

  def render(assigns) do
    Phoenix.View.render(PalapaWeb.MemberView, "_member_profile.html", assigns)
  end

  def mount(
        %{
          account_id: account_id,
          member_id: member_id,
          current_member_id: current_member_id,
          current_organization_id: current_organization_id
        },
        socket
      ) do
    account = Accounts.get!(account_id)
    Gettext.put_locale(Palapa.Gettext, account.locale)
    member = Organizations.get_member!(member_id)
    current_member = Organizations.get_member!(current_member_id)
    current_organization = Organizations.get!(current_organization_id)

    personal_informations = Organizations.list_personal_informations(member, current_member)

    {:ok,
     assign(socket, %{
       connect_params: get_connect_params(socket),
       profile_title_edit_mode: false,
       current_organization: current_organization,
       member: member,
       current_member: current_member,
       personal_informations: personal_informations
     })}
  end

  def handle_event("edit_member_title", _, socket) do
    profile_changeset = Organizations.Member.update_profile_changeset(socket.assigns.member)

    {:noreply,
     assign(socket,
       profile_title_edit_mode: true,
       profile_changeset: profile_changeset
     )}
  end

  def handle_event("update_member_title", %{"member" => member_attrs}, socket) do
    case Organizations.update_member_profile(socket.assigns.member, member_attrs) do
      {:ok, member} ->
        {:noreply, assign(socket, member: member, profile_title_edit_mode: false)}

      {:error, profile_changeset} ->
        {:noreply,
         assign(socket,
           profile_changeset: profile_changeset
         )}
    end
  end

  # update the list
  def handle_info("fetch_member_personal_informations", socket) do
    {:noreply, fetch_member_personal_informations(socket)}
  end

  def fetch_member_personal_informations(socket) do
    personal_informations =
      Organizations.list_personal_informations(
        socket.assigns.member,
        socket.assigns.current_member
      )

    assign(socket, :personal_informations, personal_informations)
  end
end

lib/palapa_web/live/member/personal_information.ex
defmodule PalapaWeb.MemberProfileLive.PersonalInformation do
  use PalapaWeb, :live_component

  alias Palapa.Organizations
  alias Palapa.Organizations.PersonalInformation

  def render(assigns) do
    Phoenix.View.render(PalapaWeb.MemberView, "_personal_information.html", assigns)
  end

  def handle_event("hide_form", _, socket) do
    socket =
      socket
      |> assign(:personal_information_changeset, nil)

    {:noreply, socket}
  end

  def handle_event("edit", _, socket) do
    changeset =
      case socket.assigns.connect_params do
        %{"stashed_form" => encoded} ->
          attrs = Plug.Conn.Query.decode(encoded)["personal_information"]

          Organizations.change_personal_information(%PersonalInformation{}, attrs)
          |> Map.put(:action, :insert)

        _ ->
          if socket.assigns.info do
            Organizations.change_personal_information(socket.assigns.info)
          else
            Organizations.change_personal_information(%PersonalInformation{})
          end
      end

    people_list =
      Enum.map(Organizations.list_members(socket.assigns.current_organization), fn m ->
        [key: m.account.name, value: to_string(Palapa.Access.GlobalId.create("palapa", m))]
      end)

    teams_list =
      Enum.map(
        Palapa.Teams.where_organization(socket.assigns.current_organization)
        |> Palapa.Teams.list(),
        fn t -> [key: t.name, value: to_string(Palapa.Access.GlobalId.create("palapa", t))] end
      )

    socket =
      socket
      |> assign(:personal_information_changeset, changeset)
      |> assign(:teams_list, teams_list)
      |> assign(:people_list, people_list)

    {:noreply, socket}
  end

  def handle_event("save", %{"personal_information" => attrs}, socket) do
    case socket.assigns.action_type do
      :create -> create_personal_information(socket, attrs)
      :update -> update_personal_information(socket, attrs)
    end
  end

  def handle_event("validate", %{"personal_information" => attrs}, socket) do
    changeset =
      Organizations.change_personal_information(%PersonalInformation{}, attrs)
      |> Map.put(:action, :insert)

    {:noreply, assign(socket, personal_information_changeset: changeset)}
  end

  def handle_event("delete", _, socket) do
    with :ok <-
           permit(
             Organizations.Policy,
             :delete_personal_information,
             socket.assigns.current_member,
             socket.assigns.info
           ) do
      case Organizations.delete_personal_information(socket.assigns.info) do
        {:ok, _deleted_info} ->
          send(self(), "fetch_member_personal_informations")
          {:noreply, socket}

        {:error, _} ->
          # FIXME: add global notice with unexpected errors
          nil
      end
    end
  end

  defp create_personal_information(socket, attrs) do
    with :ok <-
           permit(
             Organizations.Policy,
             :create_personal_information,
             socket.assigns.current_member,
             socket.assigns.current_member
           ) do
      case Organizations.create_personal_information(socket.assigns.current_member, attrs) do
        {:ok, _info} ->
          socket =
            socket
            |> assign(:personal_information_changeset, nil)

          send(self(), "fetch_member_personal_informations")
          {:noreply, socket}

        {:error, changeset} ->
          {:noreply, assign(socket, :personal_information_changeset, changeset)}
      end
    end
  end

  defp update_personal_information(socket, attrs) do
    with :ok <-
           permit(
             Organizations.Policy,
             :update_personal_information,
             socket.assigns.current_member,
             socket.assigns.info
           ) do
      case Organizations.update_personal_information(socket.assigns.info, attrs) do
        {:ok, info} ->
          socket =
            socket
            |> assign(:personal_information_changeset, nil)
            |> assign(:info, info)

          {:noreply, socket}

        {:error, changeset} ->
          {:noreply, assign(socket, :personal_information_changeset, changeset)}
      end
    end
  end
end

lib/palapa_web/views/member_view.ex
defmodule PalapaWeb.MemberView do
  use PalapaWeb, :view

  def organization_members(organization) do
    Palapa.Organizations.list_members(organization)
    |> Enum.map(fn m -> {m.account.name, m.id} end)
  end
end

lib/palapa_web/views/settings/member/member_view.ex
defmodule PalapaWeb.Settings.MemberView do
  use PalapaWeb, :view
end

lib/palapa_web/templates/member/_blankslate.html.eex
<div class="text-center mx-auto">
  <div class="blankslate">
  <i class="text-gray-500 fa fa-child"></i>&nbsp;<%= gettext("There is no member in this team yet.") %></div>
</div>

lib/palapa_web/templates/member/_member.html.eex
<%= link to: Routes.member_path(@conn, :show, @conn.assigns.current_organization, @member), class: "h-full flex flex-col items-center text-center justify-between my-1" do %>
  <%= Helpers.avatar(@member.account, :md) %>
  <div class="capitalize text-green-500"><%= @member.account.name %></div>
  <div class="text-gray-600 text-xs uppercase"><%= @member.title %></div>
<% end %>

lib/palapa_web/templates/member/_member_information.html.eex
<div class="js-member-information flex flex-col text-sm my-3 py-1 bg-gray-100 rounded-lg <%= if assigns[:new_info] && @info.id == @new_info.id do %> shadow <% end %>">
  
  <div data-target="member-information.formContainer"></div>
      
  <div data-target="member-information.content">
    <div class="flex justify-between items-center rounded-t px-2 text-gray-700 text-sm">
      <div class="font-bold text-blue-800">
        <%= @info.label %>
      </div>

      <div class="flex justify-between items-center">
        <%= if @info.private do %>
          <div class="mx-2" title="<%= PalapaWeb.MemberInformationView.visibility_text(@info) %>">
            <i class="fas fa-lock text-gray-500 mr-1"></i> <span class="text-xs">Private</span>
          </div>
        <% end %>

        <%= if Palapa.Access.permit?(Palapa.Organizations, :delete_member_information, @current_member, @info) do %>
          <div data-controller="popover" data-action="mousedown@window->popover#hide">
            <button data-target="popover.button" data-action="popover#toggle" class="m-1 bg-gray-500 rounded-full h-6 w-6 flex items-center justify-center bg-gray-500 text-blue-800 font-bold border-2 border-transparent hover:border-gray-600">
              <i class="fas fa-ellipsis-h"></i>
            </button>

            <div data-target="popover.content" class="popover hidden">
              <div data-target="popover.arrow" class="popover__arrow"></div>
              <nav class="flex flex-col">
                <%= if Palapa.Access.permit?(Palapa.Organizations, :update_member_information, @current_member, @info) do %>
                  <%= link to: member_information_path(@conn, :edit, @current_organization, @info), 
                  data: [action: "member-information#edit"], class: "popover__link" do %>
                    <i class="fas fa-pen"></i>&nbsp;Edit
                  <% end %>
                <% end %>

                <%= link to: member_information_path(@conn, :delete, @current_organization, @info),
                data: [confirm: "Are you sure you want to delete this information?", action: "member-information#delete"], class: "popover__link" do %>
                  <i class="fas fa-trash text-red-400"></i>&nbsp;Delete
                <% end %>
              </nav>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    
    <div data-controller="clipboard">
      <div class="flex justify-between p-2 text-sm">
        <div>
          <div data-target="clipboard.textToCopy">
          <%= PalapaWeb.MemberInformationView.autolink @info.value %>
          </div>

          <%= if Enum.any?(@info.attachments) do %>
            <%= for attachment <- @info.attachments do %>
              <%= link to: Palapa.Attachments.url(attachment), target: "_blank", class: "text-blue" do %>
                <br><i class="fas fa-paperclip"></i>&nbsp;<%= attachment.filename %>
              <% end %>
            <% end %>
          <% end %>
        </div>

        <button class="hidden text-xs text-gray-500 hover:text-gray-800 whitespace-no-wrap" title="Copy to clipboard" 
        data-action="clipboard#copy" data-target="clipboard.copyButton member-information.copyButton">
          <i class="fas fa-copy"></i> Copy
        </button>
      </div>

      <div data-target="clipboard.popperContent" class="js-clipboard-popper-content hidden mx-1 p-1 bg-green-500 text-xs text-white rounded">Copied to clipboard!</div>
    </div>
  </div>
</div>

lib/palapa_web/templates/member/_member_profile.html.leex
<div class="profile-main">
  <div class="flex flex-col items-center justify-center lg:w-full lg:p-2 my-4">
    <%= Helpers.avatar(@member.account, :md) %>

    <h2 class="text-green-500 text-center text-2xl font-bold capitalize mb-2"><%= @member.account.name %></h2>

    <div class="text-center text-gray-700">
      <%= if @profile_title_edit_mode do %>
        <%= form = form_for(@profile_changeset, "#", [phx_submit: "update_member_title"]) %>
          <%= text_input form, :title, placeholder: gettext("Title, position, role..."), autocomplete: "off", phx_hook: "AutoFocus", class: "input" %>
          <%= error_tag form, :title %>
          <%= submit gettext("OK"), class: "btn btn-green ml-2" %>
        </form>
      <% else %>
        <div class="text-lg font-light capitalize">
          <%= if @member.title do %>
            <%= @member.title %>
          <% else %>
            <%= if @member.id == @current_member.id do %>
              <i><%= gettext("title") %></i>
            <% end %>
          <% end %>

          <%= if @member.id == @current_member.id do %>
            <span phx-click="edit_member_title" class="cursor-pointer"><i class="fas fa-pencil-alt"></i></span>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="mt-4 text-center text-gray-700 text-xs">
      <%= unless @member.deleted_at do %>
        <div>
          <i class="fas fa-envelope mr-1"></i><%= link @member.account.email, to: "mailto:#{@member.account.email}" %>
        </div>

        <%= if @member.account.timezone do %>
          <div>
            <i class="fas fa-clock mr-1"></i><%= Helpers.account_time(@member.account) %> (<%= @member.account.timezone %>)
          </div>
        <% end %>
      <% end %>

      <%= if @member.deleted_at do %>
        <div class="text-center my-6">
          <span class="border-2 text-sm text-red-700 border-red-500 bg-gray-100 rounded-full px-4 py-2"><%= gettext("This person is no longer a member of %{workspace}", %{workspace: @current_organization.name}) %></span>
        </div>
      <% else %>
        <%= if @member.role in [:owner, :admin] do %>
          <div class="text-center my-6">
            <span class="border-2 text-sm text-gray-700 border-green-500 rounded-full px-4 py-2"><%= gettext("This member is %{role}", %{role: Gettext.dgettext(Palapa.Gettext, "enums", to_string(@member.role))}) %></span>
          </div>
        <% end %>
      <% end %>

      <%= unless @member.deleted_at do %>
        <div class="mt-4 text-center">
          <%= for team <- @member.teams do %>
            <%= Helpers.team_tag(team) %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%# https://github.com/phoenixframework/phoenix_live_view/issues/505 %>
<%#= if !@member.deleted_at do %>
  <%= render "_personal_informations.html", assigns %>
<%# end %>

lib/palapa_web/templates/member/_team_info.html.eex
<%= if @selected_team do %>
  <div class="my-4">
    <div class="flex flex-wrap justify-center self-center">

      <div class="bg-gray-200 p-3 rounded-lg text-xs font-bold m-2">
        <%= if @selected_team.private do %>
          <i class="fas fa-lock text-sm mr-2"></i><%= gettext("Private team") %>
        <% else %>
          <i class="fas fa-door-open text-sm mr-2"></i><%= gettext("Public team") %>
        <% end %>
      </div>

      <div class="bg-gray-200 p-3 rounded-lg text-xs font-bold m-2">
        <i class="fas fa-users text-sm mr-2"></i> <%= ngettext("%{count} member", "%{count} members", length(@members)) %>
      </div>

      <div class="bg-gray-200 p-3 rounded-lg text-xs font-bold m-2 text-center">
        <%= if Palapa.Teams.member?(@selected_team, @current_member) do %>
          <%= gettext("You are a member of this team") %>
          <%= link to: Routes.team_team_membership_path(@conn, :delete, @current_organization, @selected_team),
            class: "ml-2 p-1 border rounded bg-white hover:bg-gray-100 text-xs", data: [controller: "link", action: "link#delete", confirm: gettext("Are you sure you want to leave this team?")] do %>
            <i class="text-red-500 fas fa-sign-out-alt mr-2"></i><%= gettext("Leave") %>
          <% end %>
        <% else %>
          <%= if permit? Palapa.Teams.Policy, :join, @current_member, @selected_team do %>
            <%= gettext("You are not member of this team") %>
            <%= link to: Routes.team_team_membership_path(@conn, :create, @current_organization, @selected_team), class: "ml-2 border rounded bg-white hover:bg-gray-100 p-1 text-xs whitespace-no-wrap",
            data: [controller: "link", action: "link#post"] do %>
              <i class="text-green-500 fas fa-sign-in-alt mr-2"></i><%= gettext("Join") %>
            <% end %>
          <% else %>
            <%= gettext("Only an admin can invite you") %>
          <% end %>
        <% end %>
      </div>

      <%= if permit? Palapa.Teams.Policy, :edit, @current_member, @selected_team do %>
        <div class="m-2 self-center">
          <%= link gettext("Edit team"), to: Routes.team_path(@conn, :edit, @current_organization, @selected_team), class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

lib/palapa_web/templates/member/index.html.eex
<div class="content page-layout">
  <div class="main-content">
    <div class="rounded shadow bg-white">
      <div class="p-4 flex flex-wrap border-b border-gray-200 bg-white rounded-t">
        <div class="flex-1">
          <h2 class="card-header text-green-500"><%= @current_organization.name %></h2>
          <div class="text-sm uppercase text-gray-600"><%= ngettext("%{count} member", "%{count} members", @organization_members_count) %></div>
          <div class="text-sm uppercase text-gray-600"><%= ngettext("%{count} team", "%{count} teams", length(@teams)) %></div>
        </div>

        <div class="flex-1 flex flex-wrap justify-end">
          <%= if permit? Palapa.Invitations.Policy, :create, @current_member do %>
            <%= link(to: Routes.invitation_path(@conn, :new, @current_organization), class: "btn m-1") do %>
              <i class="fas fa-user-plus text-gray-600 mr-2"></i><%= gettext("Invite people to the workspace") %>
            <% end %>
          <% end %>

          <%= if permit? Palapa.Teams.Policy, :create, @current_member do %>
            <%= link(to: Routes.team_path(@conn, :new, @current_organization), class: "btn m-1") do %>
              <i class="fas fa-users text-gray-600 mr-2"></i><%= gettext("Create a team") %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="my-4 p-4">
        <%= render "_team_selector.html", assigns %>

          <%= render "_team_info.html", assigns %>
        <div class="members-grid my-8">

          <%= if Enum.any?(@members) do %>
            <%= for member <- @members do %>
              <%= render @view_module, "_member.html", %{conn: @conn, member: member} %>
            <% end %>
          <% else %>
            <%= render "_blankslate.html" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

lib/palapa_web/templates/member/show.html.eex
<div class="content large-page-layout">
  <div class="main-content">
    <div class="card">

      <div class="card-toolbar flex flex-wrap justify-center lg:justify-between">
        <%= link(to: Routes.member_path(@conn, :index, @current_organization), class: "my-auto text-gray-900 font-bold uppercase text-sm p-2") do %>
          <i class="fa fa-chevron-circle-left mr-2"></i><%= gettext("Back to your organization") %>
        <% end %>

        <%= link(gettext("Manage my account"), to: Routes.account_path(@conn, :edit), class: "btn") %>
      </div>

      <div>
        <%= Phoenix.LiveView.live_render(@conn, PalapaWeb.MemberProfileLive, session: %{
            account_id: @current_account.id,
            member_id: @member.id,
            current_member_id: @current_member.id,
            current_organization_id: @current_organization.id
          })
        %>
      </div>
    </div>
  </div>
</div>