lib/palapa_web/router.ex
defmodule PalapaWeb.Router do
  use PalapaWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(Phoenix.LiveView.Flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)

    # Sets current_account
    plug(PalapaWeb.Authentication)
    plug(PalapaWeb.Locale)
  end

  pipeline :authentication do
    plug(:enforce_authentication)
  end

  pipeline :disable_feature do
    plug(PalapaWeb.DisableFeature)
  end

  pipeline :billing do
    plug(:enforce_billing)
  end

  pipeline :organization_context do
    plug(:put_organization_context)
  end

  pipeline :contact_navigation do
    plug(PalapaWeb.ContactNavigation)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  if Mix.env() == :dev do
    forward("/emails", Bamboo.SentEmailViewerPlug)
  end

  # Public pages
  scope "/", PalapaWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)
    get("/legal", HomeController, :legal)
    get("/terms", HomeController, :terms)
    resources("/beta_subscriptions", BetaSubscriptionController, only: [:index, :create])
    resources("/registrations", RegistrationController, only: [:new, :create])
    resources("/sessions", SessionController, only: [:new, :create, :delete], singleton: true)

    resources("/password_reset", PasswordResetController,
      only: [:new, :create, :edit, :update],
      singleton: true
    )

    get("/join/:invitation_id/:token", JoinController, :new)
    post("/join/:invitation_id/:token", JoinController, :create)
  end

  # Documents public sharing
  scope(path: "/public", as: :public, alias: PalapaWeb.Public) do
    pipe_through(:browser)

    resources("/documents", DocumentController, only: [:show]) do
      resources("/pages", PageController, only: [:show])
    end
  end

  scope("/", PalapaWeb) do
    pipe_through([:browser, :authentication])

    resources("/account", AccountController, only: [:edit, :update, :delete], singleton: true)
    resources("/organizations", OrganizationController, only: [:index, :new, :create])
  end

  scope("/organizations/:organization_id", PalapaWeb) do
    pipe_through([:browser, :authentication, :organization_context])

    delete("/", OrganizationController, :delete)

    scope("/billing", Billing) do
      resources("/subscription", SubscriptionController, only: [:new, :create], singleton: true)

      post("/subscription/refresh", SubscriptionController, :refresh)

      resources("/payment_method", PaymentMethodController,
        only: [:edit, :update],
        singleton: true
      )

      resources("/payment", PaymentController, only: [:new], singleton: true)

      resources("/billing_error", BillingErrorController,
        only: [:show],
        singleton: true
      )
    end

    scope "/settings", Settings, as: :settings do
      resources("/workspace", WorkspaceController, singleton: true)
      resources("/members", MemberController, only: [:index, :delete])

      resources("/customer", Billing.CustomerController,
        singleton: true,
        only: [:show, :edit, :update]
      )

      resources("/payment_method", Billing.PaymentMethodController,
        singleton: true,
        only: [:edit, :update]
      )
    end
  end

  # Private pages for logged in members only
  scope("/organizations/:organization_id", PalapaWeb) do
    pipe_through([:browser, :authentication, :organization_context, :billing])

    get("/", MessageController, :index)
    get("/search", SearchController, :index)
    resources("/attachments", AttachmentController, only: [:create, :show])
    resources("/trash", TrashController, only: [:index])

    # --- MESSAGES

    resources("/messages", MessageController) do
      resources("/comments", MessageCommentController, only: [:create])
    end

    resources("/messages/comments", MessageCommentController, only: [:edit, :update, :delete])

    # --- DOCUMENTS

    resources("/documents", Document.DocumentController) do
      resources("/trash", Document.DocumentTrashController,
        singleton: true,
        only: [:create, :delete],
        as: :trash
      )

      resources("/public_link", Document.DocumentPublicLinkController,
        singleton: true,
        only: [:create, :delete],
        as: :public_link
      )

      resources("/sections", Document.SectionController, only: [:create])
      resources("/page", Document.PageController, only: [:new, :create])
    end

    resources("/documents/sections", Document.SectionController,
      only: [:edit, :update, :delete],
      as: :document_section
    )

    resources("/documents/pages", Document.PageController,
      only: [:show, :edit, :update, :delete],
      as: :document_page
    ) do
      resources("/suggestions", Document.SuggestionController, only: [:index, :create])
    end

    resources("/documents/suggestions", Document.SuggestionController,
      only: [:edit, :update, :delete]
    ) do
      resources("/comments", Document.SuggestionCommentController,
        only: [:create],
        as: :comment
      )

      resources("/closure", Document.SuggestionClosureController,
        only: [:create, :delete],
        as: :closure,
        singleton: true
      )
    end

    resources("/documents/suggestions/comments", Document.SuggestionCommentController,
      only: [:edit, :update, :delete]
    )

    # --- CONTACTS

    scope "/" do
      pipe_through([:contact_navigation])
      get("/contacts/export", ContactExportController, :index)
      live "/contacts", ContactLive, session: [:account_id]
      live "/contacts/new", ContactLive.New, session: [:account_id]
      live "/contacts/:id", ContactLive, session: [:account_id]
      live "/contacts/:id/edit", ContactLive.Edit, session: [:account_id]
    end

    # --- MEMBERS

    resources "/members", MemberController, only: [:index, :show] do
      resources("/teams", TeamMemberController, only: [:edit, :update], singleton: true)
    end

    resources("/invitations", InvitationController, only: [:new, :create, :delete]) do
      post("/renewal", InvitationController, :renew, as: :renew)
    end

    resources("/teams", TeamController, only: [:new, :create, :edit, :update, :delete]) do
      resources(
        "/membership",
        TeamMembershipController,
        only: [:create, :delete],
        singleton: true
      )
    end

    # --- PROFILE

    resources("/profile", ProfileController, only: [:edit, :update])
  end

  scope "/", PalapaWeb do
    pipe_through :api
    post("/stripe_webhooks", Billing.StripeWebhookController, :create)
  end

  # scope "/api", PalapaWeb do
  #   pipe_through :api
  # end
end

lib/palapa/invitations/emails.ex
defmodule Palapa.Invitations.Emails do
  import Bamboo.Email
  import Palapa.Gettext

  # Usage
  #
  # def welcome_email do
  #   new_email(
  #     to: "pierre.hurtevent@gmail.com",
  #     from: "support@myapp.com",
  #     subject: "Welcome to the app.",
  #     html_body: "<strong>Thanks for joining!</strong>",
  #     text_body: "Thanks for joining!"
  #   )

  #   # or pipe using Bamboo.Email functions
  #   new_email
  #   |> to("foo@example.com")
  #   |> from("me@example.com")
  #   |> subject("Welcome!!!")
  #   |> html_body("<strong>Welcome</strong>")
  #   |> text_body("welcome")
  # end

  def base_email() do
    new_email()
    |> from(Application.fetch_env!(:palapa, :email_transactionnal))
  end

  def invitation(%Palapa.Invitations.Invitation{} = invitation) do
    invitation =
      invitation
      |> Palapa.Repo.preload(creator: :account)
      |> Palapa.Repo.preload(:organization)

    join_link =
      PalapaWeb.Router.Helpers.join_url(PalapaWeb.Endpoint, :new, invitation.id, invitation.token)

    locale = invitation.creator.account.locale || "en"

    Gettext.with_locale(Palapa.Gettext, locale, fn ->
      base_email()
      |> to(invitation.email)
      |> subject(
        gettext("You have been invited to join \"%{workspace}\"", %{
          workspace: invitation.organization.name
        })
      )
      |> html_body("""
      <p>#{
        gettext(
          "%{creator} invited you to join the workspace \"%{workspace}\" on the Palapa application.",
          %{
            creator: invitation.creator.account.name,
            workspace: invitation.organization.name
          }
        )
      } <br><br>#{gettext("Click the following link to get started:")} <a href="#{join_link}">#{
        join_link
      }</a></p>
      """)
    end)
  end
end

lib/palapa/invitations/invitation.ex
defmodule Palapa.Invitations.Invitation do
  use Palapa.Schema

  alias Palapa.Organizations

  schema "invitations" do
    field(:email, :string)
    belongs_to(:organization, Organizations.Organization)
    belongs_to(:creator, Organizations.Member)
    timestamps()
    field(:email_sent_at, :utc_datetime)
    field(:expire_at, :utc_datetime)
    field(:token, :string)
  end
end

lib/palapa/invitations/jobs/send_invitation_job.ex
defmodule Palapa.Invitations.Jobs.SendInvitationJob do
  alias Palapa.Invitations
  alias Palapa.Invitations.Invitation

  def perform(invitation_id) do
    case Invitations.get(invitation_id) do
      %Invitation{} = invitation ->
        Invitations.send_invitation(invitation)

      _ ->
        {:ignore, "no invitation found"}
    end
  end
end

lib/palapa/invitations/join.ex
defmodule Palapa.Invitations.Join do
  use Palapa.Schema

  embedded_schema do
    field(:name)
    field(:title)
    field(:password)
    field(:timezone)
  end

  def changeset(%__MODULE__{} = registration, params) do
    registration
    |> cast(params, [:name, :title, :password, :timezone])
    |> validate_required([:name, :password])
    |> validate_length(:password, min: 8, max: 100)
    |> validate_or_nilify_timezone
    |> update_change(:name, &String.trim(&1))
    |> update_change(:title, &String.trim(&1))
  end

  # We don't want to stop the whole join process if the timezone is not found/valid.
  def validate_or_nilify_timezone(changeset) do
    tz = get_change(changeset, :timezone)

    if Tzdata.zone_exists?(tz) do
      changeset
    else
      put_change(changeset, :timezone, nil)
    end
  end

  def validate(changeset) do
    if changeset.valid? do
      {:ok, apply_changes(changeset)}
    else
      {:error, changeset}
    end
  end
end

lib/palapa/invitations/join_form.ex
defmodule Palapa.Invitations.JoinForm do
  use Palapa.Schema
  use Waffle.Ecto.Schema

  embedded_schema do
    field(:name, :string)
    field(:title, :string)
    field(:password, :string)
    field(:timezone, :string)
    field(:avatar, Palapa.Avatar.Type)
  end

  def changeset(%__MODULE__{} = form, attrs) do
    form
    |> cast(attrs, [:name, :title, :password, :timezone])
    |> validate_required([:name, :password])
    |> validate_length(:password, min: 8, max: 100)
    |> validate_or_nilify_timezone
    |> update_change(:name, &String.trim(&1))
    |> update_change(:title, &String.trim(&1))
  end

  def changeset_for_existing_account(%__MODULE__{} = form, attrs) do
    form
    |> cast(attrs, [:title])
    |> update_change(:title, &String.trim(&1))
  end

  # We don't want to stop the whole join process if the timezone is not found/valid.
  def validate_or_nilify_timezone(changeset) do
    tz = get_change(changeset, :timezone)

    if Tzdata.zone_exists?(tz) do
      changeset
    else
      put_change(changeset, :timezone, nil)
    end
  end

  def validate(changeset) do
    if changeset.valid? do
      {:ok, apply_changes(changeset)}
    else
      {:error, changeset}
    end
  end
end

lib/palapa/invitations/policy.ex
defmodule Palapa.Invitations.Policy do
  use Palapa.Policy

  def authorize(:create, %Member{role: role}, _) do
    role in [:admin, :owner]
  end

  def authorize(:delete, %Member{role: role}, _) do
    role in [:admin, :owner]
  end

  def authorize(:renew, %Member{role: role}, _) do
    role in [:admin, :owner]
  end

  # Catch-all: deny everything else
  def authorize(_, _, _), do: false
end

lib/palapa_web/controllers/invitation_controller.ex
defmodule PalapaWeb.InvitationController do
  use PalapaWeb, :controller

  alias Palapa.Invitations

  plug(:put_navigation, "member")
  plug(:put_common_breadcrumbs)

  def put_common_breadcrumbs(conn, _params) do
    put_breadcrumb(
      conn,
      gettext("Your workspace"),
      Routes.member_path(conn, :index, current_organization(conn))
    )
  end

  def new(conn, _params) do
    with :ok <- permit(Invitations.Policy, :create, current_member(conn)) do
      invitations = Palapa.Invitations.list(current_organization(conn))

      conn
      |> put_breadcrumb(
        gettext("Invite people"),
        Routes.invitation_path(conn, :new, current_organization(conn))
      )
      |> render("new.html", invitations: invitations)
    end
  end

  def create(conn, %{"invitation" => %{"email_addresses" => email_addresses}}) do
    with :ok <- permit(Invitations.Policy, :create, current_member(conn)) do
      {:ok, emails, malformed, already_member} =
        Invitations.parse_emails(email_addresses, current_organization(conn))

      Enum.each(emails, fn email ->
        Invitations.create_or_renew(email, current_member(conn))
      end)

      if Enum.any?(malformed) || Enum.any?(already_member) do
        conn
        |> put_breadcrumb(
          gettext("Invite people"),
          Routes.invitation_path(conn, :new, current_organization(conn))
        )
        |> render(
          "create.html",
          emails: emails,
          malformed: malformed,
          already_member: already_member
        )
      else
        conn =
          if Enum.any?(emails) do
            put_flash(conn, :success, gettext("Invitations have been sent"))
          else
            put_flash(conn, :error, gettext("You must enter at least one email address"))
          end

        conn
        |> redirect(to: Routes.invitation_path(conn, :new, current_organization(conn)))
      end
    end
  end

  def delete(conn, %{"id" => id}) do
    invitation = Invitations.visible_to(current_member(conn)) |> Invitations.get!(id)

    with :ok <- permit(Invitations.Policy, :delete, current_member(conn), invitation),
         {:ok, _invitation} = Invitations.delete(invitation) do
      send_resp(conn, :no_content, "")
    end
  end

  def renew(conn, %{"invitation_id" => invitation_id}) do
    invitation = Invitations.visible_to(current_member(conn)) |> Invitations.get!(invitation_id)

    with :ok <- permit(Invitations.Policy, :renew, current_member(conn), invitation),
         {:ok, new_invitation} <-
           Invitations.create_or_renew(invitation.email, current_member(conn)) do
      conn
      |> put_flash(
        :success,
        gettext("%{email} has been sent a new invitation", %{
          email: new_invitation.email
        })
      )
      |> redirect(
        to:
          Routes.invitation_path(conn, :new, current_organization(conn), %{
            "renewed" => new_invitation.id
          })
      )
    end
  end
end

lib/palapa_web/views/invitation_view.ex
defmodule PalapaWeb.InvitationView do
  use PalapaWeb, :view

  def sent_a_minute_ago?(invitation) do
    if invitation.email_sent_at do
      a_minute_after_sending = Timex.shift(invitation.email_sent_at, minutes: 1)
      Timex.after?(DateTime.utc_now(), a_minute_after_sending)
    else
      false
    end
  end
end

lib/palapa_web/templates/invitation/_form.html.eex
<%= form_for @conn, Routes.invitation_path(@conn, :create, @conn.assigns.current_organization), [as: :invitation], fn form -> %>
  <p><%= gettext("Enter one email address per line:") %></p>

  <div class="field">
    <%= textarea form, :email_addresses, value: @prefill, class: "w-full h-24 border", tabindex: 1 %>
  </div>

  <div class="card-actions">
    <%= submit gettext("Send invitations"), class: "btn btn-green", tabindex: 1 %>
  </div>
<% end %>

lib/palapa_web/templates/invitation/_invitation.html.eex
<div data-controller="invitation" class="p-4 flex flex-col lg:flex-row flex-wrap border-t text-sm">
  <div class="flex-1 py-2"><%= @invitation.email %></div>
  <div class="py-2 pr-2"><%= gettext("Sent") %> <%= Helpers.auto_format_datetime(@conn, @invitation.inserted_at) %></div>
  <div class="flex">
    <%= if Application.get_env(:palapa, :env) == :dev || sent_a_minute_ago?(@invitation) do %>
      <%= link gettext("Send again"), to: Routes.invitation_renew_path(@conn, :renew, @current_organization, @invitation),
        method: "post",
        class: "btn",
        tabindex: 1,
        data: [
          target: "invitation.renewButton",
          controller: "link",
          action: "link#post"
        ]
      %>
    <% end %>

    <%= link gettext("Cancel"), to: Routes.invitation_path(@conn, :delete, @current_organization, @invitation),
      class: "btn btn-red ml-2",
      tabindex: 1,
      data: [
        target: "invitation.cancelButton",
        action: "invitation#cancel",
        confirm: gettext("Are you sure you want to cancel this invitation?")
      ]
    %>
  </div>
</div>

lib/palapa_web/templates/invitation/create.html.eex
<div class="content page-layout">
  <div class="main-content">
    <div class="card p-1 lg:p-8">
        <h2 class="card-header">
          <%= gettext("Invite people") %>
        </h2>

        <div class="card-header-separator"></div>

        <%= if Enum.any? @emails do %>
          <p class="text-green-500 font-bold my-2"><i class="fas fa-check-circle mr-2"></i><%= ngettext("%{count} invitation has been sent successfully!", "%{count} invitations have been sent successfully!", Enum.count(@emails)) %></p>
          <ul class=" bg-green-100 rounded h-24 p-2 my-2 overflow-scroll">
            <%= for email <- @emails do %>
              <li><%= email%></li>
            <% end %>
          </ul>
        <% end %>

        <%= if Enum.any? @already_member do %>
          <p class="text-green-500 font-bold my-2"><i class="fas fa-check-circle mr-2"></i><%= ngettext("%{count} person is already member of your organization!", "%{count} people are already members of your organization!", Enum.count(@already_member)) %> </p>
          <ul class=" bg-green-100 rounded h-24 p-2 my-2 overflow-scroll">
            <%= for email <- @already_member do %>
              <li><%= email%></li>
            <% end %>
          </ul>
        <% end %>

        <%= if Enum.any? @malformed do %>
          <p class="textred-500font-bold"><i class="fas fa-times-circle mr-2"></i><%= ngettext("%{count} invitation couldn't be sent", "%{count} invitations couldn't be sent", Enum.count(@malformed)) %></p>
          <p><%= gettext("Make sure addresses are correct and well formatted and try again.") %></p>

          <%= render PalapaWeb.InvitationView, "_form.html", conn: @conn, prefill: Enum.join(@malformed, "\n") %>
        <% end %>
        <%= link gettext("Go back to invitations"), to: Routes.invitation_path(@conn, :new, @conn.assigns.current_organization), class: "btn" %>
    </div>
  </div>
</div>

lib/palapa_web/templates/invitation/new.html.eex
<div class="content page-layout">
  <div class="main-content">
    <div class="card p-1 lg:p-8">
      <h2 class="card-header"><%= gettext("Invite people") %></h2>
      <div class="card-header-separator"></div>

      <%= render PalapaWeb.InvitationView, "_form.html", conn: @conn, prefill: nil %>
    </div>

    <%= if Enum.any?(@invitations) do %>
      <div id="pending_invitations_container" class="card my-8">
        <div class="border-b border-gray-200 rounded-t">
          <h2 class="card-header p-4"><%= gettext("Pending invitations") %></h2>
            <div id="pending_invitations_list">
              <%= for invitation <- @invitations do %>
                <%= render "_invitation.html", Map.put(assigns, :invitation, invitation) %>
              <% end %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>